### ISSUE TITLE
Parsing package issue

### ISSUE THREAD

**Issue by AhmerAfzal1** [elliot619/AppUpdater#1]
I'm using this great library but facing a issue after download "There was a problem while parsing the package"
![screenshot_20170802-100604](https://user-images.githubusercontent.com/11347099/28858553-c301d2ca-776a-11e7-9c27-3ed2cbb9a08c.png)

**Comment by elliot619** [comment]
This is an issue not related to this library, either there was a problem while downloading the APK and it got corrupted or the APK is corrupted from build.
